[BRO] Prototype Ability implementation
magefree/mage pull request #10062
Opened 2023-02-23 19:42 UTC by Susucre

Hello,
This is my take on implementing the Prototype Ability from Brother's War. e.g. [[Blitz Automaton]]

I went with introducing a prototyped boolean for both Permanents and Spells. That is set to true upon casting a spell with a prototype SpellAbility then propagated on cast, resolve, copy (both copy on stack & battlefield) and clone.
Then, a few continuousEffect are added through PrototypeActivity, that conditionnaly set Color, ManaCost, and base Power/Toughness for potentially prototyped cards.

The only weird behavior I've noticed testing the ability is that on cancelling the cast of a prototyped spell, the card wrongly display the prototyped power/toughness back in the hand, but that does not look to alter how the cast behave from there.

2023-02-24 14:29 UTC, Susucre commented
[[Blitz Automaton]]

Also, solves part of BRO set tracking #9598

2023-04-11 00:46 UTC, theelk801 requested changes
would you be able to write tests for this? it needs a pretty comprehensive test suite

2023-04-11 00:46 UTC, theelk801 commented on Mage/src/main/java/mage/abilities/keyword/PrototypeAbility.java
> +    public PrototypeAbility(Card card, String manaString, ObjectColor color, int power, int toughness) {
why do we need to pass in color here? the mana cost should be enough info for that

2023-04-26 00:48 UTC, Susucre commented
Hey there!
Sorry I got no time at all to dedicate to the project right now.
Both unit tests and deriving the prototype color from the manacost are worth additions.
Feel free to take over the branch or start fresh, I will not have time for improving this until at least June.

2023-04-26 00:49 UTC, theelk801 commented
Hey, thanks for responding! I'll probably take over this branch. Thanks for all the work you've done so far.

2023-04-26 01:29 UTC, theelk801 commented
switching this over to #10280

2023-04-26 01:29 UTC, closed without merging