[LTR] Implement Gandalf, White Rider
magefree/mage pull request #10538
Opened 2023-06-28 11:28 UTC by TiagoMDG

* Took ideas from the God Eternals, Arwen Undomiel and Enigma Sphinx.
* Tested it with multiple interactions, including murdering a stolen Gandalf with Agent of Treachery.

2023-06-29 02:37 UTC, xenohedron requested changes

2023-06-29 02:37 UTC, xenohedron commented on Mage.Sets/src/mage/cards/g/GandalfWhiteRider.java
> +        this.addAbility(new GandalfWhiteRiderTriggeredAbility(new GandalfWhiteRiderDyingEffect(), true));
Why not use `DiesSourceTriggeredAbility` ?

2023-06-29 02:37 UTC, xenohedron commented on Mage.Sets/src/mage/cards/g/GandalfWhiteRider.java
> +        Card card = (Card) source.getSourceObjectIfItStillExists(game);
This doesn't look right... need to check the zcc (compare to the "permanentLeftBattlefield" value stored from DiesSourceTriggeredAbility)

2023-06-29 02:37 UTC, xenohedron commented on Mage.Sets/src/mage/cards/g/GandalfWhiteRider.java
> +                new BoostControlledEffect(1, 0, Duration.EndOfTurn).setText("creatures you control get +1/+0 until end of turn"),
nit, is there a reason this text needs to be set manually? seems straightforward enough that auto generation should be correct

2023-06-30 02:00 UTC, TiagoMDG commented
Going to push the zcc comparison in a bit.

2023-06-30 02:00 UTC, xenohedron approved these changes

2023-06-30 02:01 UTC, xenohedron commented
> Going to push the zcc comparison in a bit.

oh right good call

2023-06-30 02:37 UTC, merged