Fix Ring-bearer choosing & add some GUI + logs
magefree/mage pull request #10596
Opened 2023-07-08 18:59 UTC by Susucre

Aside from the cog being placeholder (I can try to make a ring.svg, but do not hope for much),
this should improve the feedback on what happened on ring tempting a player (with logs, and info + icon on the ringbearer) 

In addition, there was a few wrong paths in the ring bearer chosing logic.
If there is at least one creature, there should always be a ring bearer chosen event.

I pondered adding an info on the ring emblem to tell that there is (or there is none) Ringbearer at the moment.
Did not feel critical enough.

![ringbearing](https://github.com/magefree/mage/as
![ringtempting](https://github.com/magefree/mage/assets/34709007/dfa57d5b-5457-4b35-baf3-f302b318f6ca)
sets/34709007/8e9ba955-f842-4918-b47e-a59c6c8ae8bf)

solve #10572 (once there is a proper svg.)
fix #10453 maybe ? The logic has been redone, and there is now game logs to be sure that something that should have happen did not.

2023-07-08 19:09 UTC, thefnitalian commented
Use https://www.vectorstock.com/royalty-free-vector/diamond-ring-icon-vector-33131789

2023-07-08 19:23 UTC, Susucre commented
Won't do, I think we specifically need svg, and probably of a set ratio.

2023-07-08 19:47 UTC, JayDi85 commented
[readme-icons.txt](https://github.com/magefree/mage/blob/master/Mage.Client/src/main/resources/card/icons/readme-icons.txt) contains recommendation and sources for the icon resources.

Good example:
https://icons.getbootstrap.com/icons/record-circle-fill/
![shot_230708_234501](https://github.com/magefree/mage/assets/8344157/f45236e3-7b43-4cb8-92ca-6cdb586287e4)



BTW icons engine support any sides and any order for the icons (left, center, right, combined order). Test tools contains test render dialog with icons support (must enable cards with icons in the code to see in it).

If ring status is a critical for the whole game then it can be put to the top as except. Also it can be with custom yellow/gold color. See commander icon for example.

2023-07-08 20:30 UTC, alexander-novo commented
https://icons8.com/icon/41528/one-ring

This one has an attribution license. Just need to add a link in an about page

2023-07-08 21:14 UTC, Susucre commented
Thanks @alexander-novo , really like that one.
Since I do want it to stand out, it needs to be on another panel to have its own color. I positioned it right for now, if someone has strong opinions about it, feel free to change it later on.
![rightsideringbearer](https://github.com/magefree/mage/assets/34709007/051a6a20-399d-47c8-b8d2-2281dc71962a)

As for the attribution license, they seem to be fine with open source projects, I did add it in the readme, and the source svg in a new dedicated folder. Is that enough?

2023-07-08 21:17 UTC, alexander-novo commented
https://icons8.com/license

No, they specify that desktop applications must have a link in the about section

2023-07-08 21:21 UTC, Susucre commented
Uhm I'll try to find how to modify it then

2023-07-08 21:26 UTC, JayDi85 commented
icons8 is weird source for the project and must be removed. Use sources with cc/mit license styles without things like "Add a link to icons8.com on all pages using our content. If that's most pages, a link in your footer is fine."

2023-07-08 21:27 UTC, alexander-novo commented
I think it's fine to get rid of this as a source, but I do want to point out the desktop application section, rather than the website section.

2023-07-08 21:41 UTC, Susucre commented
Going to use this one: https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/fontawesome-free/svgs/solid/ring.svg

2023-07-08 21:44 UTC, alexander-novo commented
Oh that looks good too

2023-07-08 21:56 UTC, JayDi85 commented
> There are only so many sides to cards.

Yes, the main idea behind card panels -- icons from one panel can be auto-sorted and combined (if it catch too much items):
 - if you put one icon to the centred panel then you got "x x O x x"
 - if you put two icons to the centred panel then you got "x O O x x"
 - if you put three icons to the centred panel then you got "x O O O x"

BTW right side/corner of the card will be used for counters someday, see #8149

2023-07-08 22:40 UTC, JayDi85 requested changes

2023-07-08 22:52 UTC, Susucre commented on Mage/src/main/java/mage/players/PlayerImpl.java
> +        bearer.addInfo(ringbearerInfoKey, null, game);
There is two problems with that:
- The ring bearer status is lost when you lose the control of the permanent. I think that was the intent for clearing ringBearerId in that function.
- Ring Bearer status has nothing to do with layers. We could reimplement it as a tapped status by adding a boolean isRingBearer to all Permanents if that helps with the engine.

2023-07-08 23:15 UTC, Susucre commented
We could use an icon color overwrite inside an icon panel. I will not bother with it in this PR however. The red used for the commander icon is very bright and the ring svg is a little too wide for that color.
![ringred](https://github.com/magefree/mage/assets/34709007/9a19296a-78a0-41ed-b0a3-146ec614ae04)

For reference, the GOLD color added looks like that. Not that great, but less in your face.
![ring](https://github.com/magefree/mage/assets/34709007/5792678d-bada-4266-b817-bf52616b3382)

2023-07-08 23:17 UTC, alexander-novo commented
I think it could use some combination of the SVG being scaled down a bit and the top row moving up a little bit as right now while the crown doesn't get drawn over the text, the ring does and both of them conflict with the mana cost.

2023-07-08 23:26 UTC, JayDi85 commented on Mage/src/main/java/mage/players/PlayerImpl.java
> +        bearer.addInfo(ringbearerInfoKey, null, game);
> I think that was the intent for clearing ringBearerId in that function.

well, I see... There is much more complex problem with original implementation.

Restore code contains:
`this.ringBearerId = player.getRingBearerId();`

But `getRingBearerId` writing some code. Copy and restore constructors must be simple, without any additional/writing logic in the middle of the restore procedure. So bearer modification code must be removed at all.

For new implementation:
* 701.52a Certain spells and abilities have the text “the Ring tempts you.” Each time the Ring tempts you, choose a creature you control. That creature becomes your Ring-bearer **until another creature becomes your Ring-bearer or another player gains control of it**.
* 701.52b Ring-bearer is a designation **a permanent can have**. Being a Ring-bearer is not a copiable value.
* So permanent must have a flag, not a player;
* Flag must not be a copyable for copy effects;
* `getRingBearerId` must be dynamic with Game param to find an actual id;
* bearer set in two places: on new bearer choose, on `checkControlChanged` (it must call additional method like `removeUncontrolledBearer`).

2023-07-09 10:22 UTC, Susucre commented on Mage/src/main/java/mage/players/PlayerImpl.java
> +        bearer.addInfo(ringbearerInfoKey, null, game);
Alright, that ended up less complex that I thought.
Please let me know if anything is wrong in the new implementation.
The isRingbearer logic is now at the charge of the PermanentImpl class.

2023-07-09 10:25 UTC, Susucre commented
Added another game log message on control loss of the ring bearer:
![lostcontrolringbearer](https://github.com/magefree/mage/assets/34709007/388e2fea-3e5c-4bce-a92e-f44dc4fbdd9e)

This has become more of a general rework of the mechanic that just GUI improvment.
I'll let the fine tuning of the ring icon to another PR, I am not great at the whole svg tweaking.

2023-07-10 00:23 UTC, JayDi85 approved these changes
Some little fixes needs, but all other are fine now.

2023-07-10 00:23 UTC, JayDi85 commented on Mage/src/main/java/mage/players/PlayerImpl.java
> +            game.fireEvent(GameEvent.getEvent(GameEvent.EventType.RING_BEARER_CHOSEN, currentBearer.getId(), null, getId()));
miss null check for currentBearer

2023-07-10 00:23 UTC, JayDi85 commented on Mage/src/main/java/mage/players/PlayerImpl.java
> +            game.informPlayers(getLogName() + " has chosen " + ringBearer.getLogName() + " as Ring-bearer.");
miss null check for ringBearer

2023-07-10 00:23 UTC, JayDi85 commented on Mage/src/main/java/mage/players/PlayerImpl.java
>          }
`RING_BEARER_CHOSEN` event must be called after `setRingBearer`, so triggers will see actual state of the battlefield and ring bearers.

2023-07-12 03:54 UTC, xenohedron approved these changes

2023-07-12 23:40 UTC, merged