Pillars of the Paruns custom mode
magefree/mage pull request #10633
Opened 2023-07-16 14:10 UTC by Susucre

This requires #10629 and #10632 first. I'll rebase once a version of those get merged.

So I am working on a custom game mode. Is it alright to merge it in the code base, or should I convince some server maintainers to add the .jar to their server's plugins?
Once we have [custom options for the number of starting cards in hand](https://github.com/magefree/mage/issues/10551) and [Emblem cards](#10498), I could replace the custom mode by a custom emblem to despecialize the game mode.

As for the custom game mode, here are the changes from an usual limited match:
- The starting hand size is 6
- At the beginning of each player's main step, that player conjure Pillar of the Paruns on the battlefield. This counts as a land played for the turn.

2023-07-16 14:11 UTC, Susucre commented
[[Pillar of the Paruns]]

2023-07-16 15:04 UTC, JayDi85 requested changes

2023-07-16 15:04 UTC, JayDi85 commented on Mage.Server.Plugins/Mage.Game.PillarOfTheParunsDuel/src/mage/game/PillarOfTheParunsDuel.java
> +public class PillarOfTheParunsDuel extends GameImpl {
Must add game mode description, rules and other information here as docs/comments. If it's an official/public then must contains link to the public page/wiki.

2023-07-16 15:09 UTC, JayDi85 commented
Also please test that game mode and effects with [[Karn Liberated]] -- is it works fine and without errors after game restart.

2023-07-16 15:11 UTC, Susucre commented on .gitignore
> +Mage.Server.Plugins/Mage.Game.PillarOfTheParunsDuel/target/
ok! This is definitively a custom format and not an official one.

2023-07-16 15:11 UTC, Susucre commented
Oh right, it is possible to restart the game that way, will definitively test that.

2023-07-18 04:55 UTC, JayDi85 approved these changes

2023-07-18 04:55 UTC, merged