[WOE] Implement Not Dead After All
magefree/mage pull request #10916
Opened 2023-08-20 10:24 UTC by Susucre

2023-08-20 10:24 UTC, Susucre commented
[[Not Dead After All]]

2023-08-22 02:33 UTC, xenohedron requested changes

2023-08-22 02:33 UTC, xenohedron commented on Mage.Sets/src/mage/cards/n/NotDeadAfterAll.java
> +        this.getSpellAbility().addTarget(new TargetCreaturePermanent());
TargetControlledCreaturePermanent

2023-08-22 13:16 UTC, xenohedron approved these changes

2023-08-22 13:45 UTC, merged