[WOE] Implement Pollen-Shield Hare
magefree/mage pull request #10932
Opened 2023-08-21 22:47 UTC by Susucre

2023-08-21 22:47 UTC, Susucre commented
![image](https://github.com/magefree/mage/assets/34709007/8dd3b49b-b80b-46a0-8b94-dc934b9c463d)

2023-08-22 01:19 UTC, theelk801 requested changes

2023-08-22 01:19 UTC, theelk801 commented on Mage.Sets/src/mage/cards/p/PollenShieldHare.java
> +    private static final Hint hint = new ValueHint("Number of controlled creatures", xValue);
you can use `CreaturesYouControlCount` and `CreaturesYouControlHint` here

2023-08-22 01:19 UTC, theelk801 commented on Mage.Sets/src/mage/cards/p/PollenShieldHare.java
> +                new BoostAllEffect(1, 1, Duration.WhileOnBattlefield, filter, false)
this can be `BoostControlledEffect` with `StaticFilters.FILTER_CREATURE_TOKENS`

2023-08-22 01:19 UTC, theelk801 commented on Mage.Sets/src/mage/cards/p/PollenShieldHare.java
> +                        .setText("Target creature you control gains vigilance")
it doesn't matter here but I like to leave the first letter of the text lowercase as a habit and let the text generation deal with it

2023-08-22 01:19 UTC, theelk801 commented on Mage.Sets/src/mage/cards/p/PollenShieldHare.java
> +                        .setText(" and gets +X/+X until end of turn, where X is the number of creatures you control.")
you don't need the space before "and"

2023-08-25 01:19 UTC, theelk801 approved these changes

2023-08-25 01:20 UTC, merged