[WOE] Implement Collector's Vault
magefree/mage pull request #10963
Opened 2023-08-22 21:58 UTC by Susucre

2023-08-22 23:43 UTC, theelk801 requested changes

2023-08-22 23:43 UTC, theelk801 commented on Mage.Sets/src/mage/cards/c/CollectorsVault.java
> +        ability.addEffect(new TapSourceEffect());
this needs to be `TapSourceCost`

2023-08-23 05:01 UTC, Susucre commented on Mage.Sets/src/mage/cards/c/CollectorsVault.java
> +        ability.addEffect(new TapSourceEffect());
Oops indeed.

2023-08-24 00:36 UTC, xenohedron approved these changes

2023-08-24 00:40 UTC, merged