[WOE] Implement Virtue of Strength
magefree/mage pull request #10988
Opened 2023-08-24 09:36 UTC by Susucre

2023-08-24 09:36 UTC, Susucre commented
[[Virtue of Strength]]

2023-08-25 01:16 UTC, theelk801 requested changes

2023-08-25 01:16 UTC, theelk801 commented on Mage.Sets/src/mage/cards/v/VirtueOfStrength.java
> +        this.getSpellCard().getSpellAbility().addEffect(new ReturnToHandTargetEffect());
this should be `ReturnFromGraveyardToHandTargetEffect`

2023-08-25 01:16 UTC, theelk801 commented on Mage.Sets/src/mage/cards/v/VirtueOfStrength.java
> +    private static final FilterCard filter = new FilterCard("creature or land card from a graveyard");
this should be "from your graveyard"

2023-08-27 01:03 UTC, xenohedron approved these changes

2023-08-27 19:10 UTC, merged