[WOE] Implement Elusive Otter
magefree/mage pull request #10991
Opened 2023-08-24 10:27 UTC by Susucre

2023-08-24 10:28 UTC, Susucre commented
[[Elusive Otter]]

2023-08-28 22:06 UTC, theelk801 requested changes
I think this should probably be split into two separate PRs, I have some notes on the refactor though

2023-08-28 22:06 UTC, theelk801 commented on Mage.Sets/src/mage/cards/e/ElusiveOtter.java
> +        this.addAbility(new SimpleStaticAbility(Zone.BATTLEFIELD, new CantBeBlockedByCreaturesWithLessPowerEffect()));
you can remove the zone param here

2023-08-28 22:06 UTC, theelk801 commented on Mage/src/main/java/mage/target/common/TargetUpToCreaturePermanentAmount.java
> +public class TargetUpToCreaturePermanentAmount extends TargetPermanentAmount {
if we're gonna have a special class for the "up to" case then it should probably be for any permanent rather than for just creatures

2023-08-28 22:50 UTC, Susucre commented
I'll make a separate PR for the otter without the new Target.
Closing this PR to keep some trace of it, but probably will have another form anyway.

2023-08-28 22:50 UTC, closed without merging