[WOC] Implement Loamcrafter Faun
magefree/mage pull request #11018
Opened 2023-08-25 17:39 UTC by xanderhall

Manually tested, effect seemed to work correctly.

2023-08-25 17:39 UTC, xanderhall commented
[[Loamcrafter Faun]]

2023-08-26 00:15 UTC, xenohedron requested changes

2023-08-26 00:15 UTC, xenohedron commented on Mage.Sets/src/mage/cards/l/LoamcrafterFaun.java
> +    private static FilterCard filter = new FilterPermanentCard("nonland permanent(s) in your graveyard");
is there a reason the text doesn't match the card? "nonland permanent cards from your graveyard"

2023-08-26 00:15 UTC, xenohedron commented on Mage.Sets/src/mage/cards/l/LoamcrafterFaun.java
> +        this.addAbility(new EntersBattlefieldAbility(new LoamcrafterFaunDiscardEffect()));
EntersBattlefieldTriggeredAbility

2023-08-26 20:41 UTC, xenohedron approved these changes

2023-08-26 20:46 UTC, merged