[WOC] Implement Shadow Puppeteers
magefree/mage pull request #11183
Opened 2023-09-19 11:43 UTC by Susucre

The tweak of `BecomesCreatureTargetEffect` was due to the following ruling:
> If the creature stops being a creature before Shadow Puppeteers's last ability resolves, it will become red until end of turn in addition to its other colors. Since it's not a creature, it won't gain the Dragon subtype, and it won't have base power and toughness 4/4.

So with the trigger on the stack, removing the Creature type does end up with a red non-creature.
![image](https://github.com/magefree/mage/assets/34709007/4f3a5df8-ea4b-4b2b-9e67-544e4974b3a3)
(and back to colorless land when end of turn effect cleared up)

2023-09-19 11:44 UTC, Susucre commented
[[Shadow Puppeteers]]

2023-09-23 23:36 UTC, xenohedron requested changes
`BecomesCreatureTargetEffect` is already messy and I don't want to add another constructor parameter there. Plus it would need extra handling for the "in addition to its other colors". I know we already do something similar in `BecomesCreatureSourceEffect`, but for this use case I would rather use the individual effects to add color, subtype, and base P/T. Unless you think it would be cleaner to just make a custom effect for this card.

2023-09-24 14:29 UTC, Susucre commented
Alright, makes more sense too since the effect is not making a non Creature become a Creature either, just give the subtype Dragon if it is possible (Creature or Tribal).

I went with the custom effect, I personally find that cleaner to have every modification together, altough it is applied on 3 different layers.

2023-09-24 17:32 UTC, xenohedron approved these changes

2023-09-25 02:09 UTC, merged