[WHO] Implement TARDIS
magefree/mage pull request #11803
Opened 2024-02-17 01:22 UTC by skiwkr

#10653
First pull request, let me know if any issues :)

2024-02-17 02:16 UTC, xenohedron requested changes
bunch of style nits and an extraneous ability, but generally on the right track

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +    private static final FilterControlledPermanent TimeLordFilter = new FilterControlledPermanent();
naming convention: fields/methods are not capitalized (only classes). Since only one filter can just call it `filter`

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +    static {TimeLordFilter.add(SubType.TIME_LORD.getPredicate());}
style: newline after opening brace and before closing brace

```java
static {
    // your code here
}
```

but also, you can just put `SubType.TIME_LORD` in the constructor of `FilterControlledPermanent` so you don't need a static block at all

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +    private static final Condition condition = new PermanentsOnTheBattlefieldCondition(TimeLordFilter, ComparisonType.MORE_THAN, 1);
This doesn't look right- you only need one Time Lord, not more than one. (constructor argument with only filter parameter automatically adds more than zero)

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +                new PermanentsOnTheBattlefieldCondition(TimeLordFilter),
use the `condition` you defined above

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +        Ability TardisAttackTrigger = new ConditionalInterveningIfTriggeredAbility(
naming convention again, don't capitalize (and can just call this `ability`)

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +                "Whenever TARDIS attacks, if you control a Time Lord, the next spell you cast this turn has cascade, and you may planeswalk.");
use `{this}` to generate card name in place of `TARDIS`

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +		this.addAbility(TardisAttackTrigger);
this shouldn't be indented

2024-02-17 02:16 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TARDIS.java
> +        this.addAbility(new CastOnlyIfConditionIsTrueAbility(condition).addHint(hint));
This seems not at all relevant and should be removed.
(add the hint to the attack trigger)

2024-02-21 01:16 UTC, skiwkr commented
I think all the changes requested were made, I'm confused why the hint needs to be a part of the ability though and not it's own, is that just a style thing?

2024-02-21 05:38 UTC, xenohedron approved these changes

2024-02-21 05:39 UTC, xenohedron commented
Hints are associated with abilities, and style is definitely to use exiting abilities and not make fake ones to store hints. Card view will collect all hints and display appropriately below all ability text.

2024-02-21 05:53 UTC, merged

2024-02-21 05:53 UTC, xenohedron commented
Thanks for the contribution