[ANB] extra cards
magefree/mage pull request #11872
Opened 2024-02-28 09:23 UTC by tiera3

Baloth Packhunter
Compound Fracture
Hallowed Priest
Mardu Outrider
Tin Street Cadet

2024-02-29 02:32 UTC, xenohedron requested changes
"becomes blocked" is subtly different from "becomes blocked by a creature", so need to use the right class for it.

Rest looks good.

2024-02-29 02:32 UTC, xenohedron commented on Mage.Sets/src/mage/cards/m/MarduOutrider.java
> +import mage.abilities.Ability; // not sure about this line - think it is not needed
fyi - Unused imports are harmless, though I certainly recommend just having your IDE manage that sort of thing automatically

2024-02-29 02:32 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TinStreetCadet.java
> +        this.addAbility(new BecomesBlockedByCreatureTriggeredAbility(new CreateTokenEffect(new GoblinToken()), false));
this one should be `BecomesBlockedSourceTriggeredAbility`

2024-03-01 17:47 UTC, JayDi85 approved these changes

2024-03-01 17:47 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/c/CompoundFracture.java
> +    private static final DynamicValue xValue = new CardsInControllerGraveyardCount(filter, -1);
For info, not pr. If you see xValue then it’s a good point to add some card hint about calculated value for a user. Current example: dynamic card hint with “com fra cards in your graveyard: 123”

2024-03-01 17:49 UTC, merged