[PIP]Implement Robobrain War Mind
magefree/mage pull request #11972
Opened 2024-03-19 04:41 UTC by justinjohnson14

Sorry for creating a second one I'm still new to git and got scared lol.

2024-03-19 05:02 UTC, xenohedron requested changes

2024-03-19 05:02 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RobobrainWarMind.java
> +        this.addAbility(new EntersBattlefieldTriggeredAbility(new GetEnergyCountersControllerEffect(ArtifactYouControlCount.instance)));
wrong dynamic value, needs to be artifact creatures, not artifacts, you control

use PermanentsOnBattlefieldCount with appropriate filter, both declared static

2024-03-19 05:30 UTC, justinjohnson14 commented
I give up i apparently don't know what I am doing.

2024-03-19 06:31 UTC, ssk97 commented
> I give up i apparently don't know what I am doing.

You want to create a new branch from master each time you want to make a new Pull Request. You can always check to see which branch you're currently in.

2024-03-20 03:32 UTC, justinjohnson14 commented
If this pull request gets closed. Can I commit changes to main without it getting attached to this pull request again? I plan to make named branches for card implementations now but just wondering for future reference.

2024-03-21 02:30 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RobobrainWarMind.java
> +class RobobrainWarMindEffect extends OneShotEffect {
Don't make a new effect class. Use `GetEnergyCountersControllerEffect`

2024-03-23 04:20 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RobobrainWarMind.java
> +        this.addAbility(new AttacksTriggeredAbility(new DoIfCostPaid(new DrawCardTargetEffect(1, false), new PayEnergyCost(3))));
use `DrawCardSourceControllerEffect`, this isn't targeted.

2024-03-23 04:22 UTC, xenohedron commented
> If this pull request gets closed. Can I commit changes to main without it getting attached to this pull request again? I plan to make named branches for card implementations now but just wondering for future reference.

Once the PR is closed/merged it'll be fine. What I recommend is after this gets merged, to reset the master branch of your fork to magefree:master.

2024-03-24 02:40 UTC, xenohedron approved these changes

2024-03-26 01:33 UTC, merged

2024-03-26 01:35 UTC, xenohedron commented
thanks for the contribution