Introduce a new layer 0 for transform characteristics
magefree/mage pull request #12055
Opened 2024-04-03 11:27 UTC by DominionSpy

Fixes #11683 

As discussed in the issue above and #11677, this introduces a new layer 0 for transform characteristics. This is done so that the effect of a transformed permanent can be applied before any effects in layer 1 (copy effects).

2024-04-03 11:29 UTC, DominionSpy commented
I'm not sure how to go about writing tests for this without a card example. There are no existing implemented cards that are affected by this issue.

2024-04-03 15:33 UTC, jeffwadsworth commented
If you have the Paleontologist's Pick-Axe // Dinosaur Headdress implemented using this code, I assume you were able to test it.  Is that correct?  That card looked like it had some requested changes to be made, etc.

2024-04-03 16:53 UTC, JayDi85 requested changes
Test framework allows to construct any cards with any abilities (activated, static, etc). If you don't have real card or it hard to use for some use cases then use `addCustomCardWithAbility`.

Such global game engine changes must be merged with some unit tests (test must works in new version and fails in old version).

P.S. It's not about changes -- old PR #11677 has same problems with lack of tests and proofs.

2024-04-04 08:49 UTC, DominionSpy commented
> Test framework allows to construct any cards with any abilities (activated, static, etc). If you don't have real card or it hard to use for some use cases then use `addCustomCardWithAbility`.

I've had a look into this, but I can't see how I can set up a DFC with transform.
To test this, I at least need to have a transformed card with a copy effect on it.

2026-05-25 02:45 UTC, closed without merging