Attempt at a Download Basic Lands option
magefree/mage pull request #12283
Opened 2024-05-23 14:49 UTC by tiera3

https://github.com/magefree/mage/issues/12272

Possible improvement - filter sets to only those that include basic lands.

I also only put in the five main basics. I wasn't sure whether to include the Snow-Covered Basics so left them out (primarily because they cannot be freely added to limited decks, but could see an argument to include them because they can be added to constructed decks.)

Wastes was deliberately excluded because it cannot be freely added to decks.

2024-05-23 14:56 UTC, tiera3 commented
Note this has a modified file in common with https://github.com/magefree/mage/pull/12282 , so if one gets accepted, the other will need to be rebased before continuing.

2024-05-25 22:41 UTC, xenohedron requested changes
Agree with not including snow-covered or wastes for this purpose.

Please fix style - spaces, not tabs.

2024-05-25 22:41 UTC, xenohedron commented on Mage.Client/src/main/java/org/mage/plugins/card/images/DownloadPicturesService.java
> +					static final List<String> basicList = Arrays.asList("Plains", "Island", "Swamp", "Mountain", "Forest");
declare this as a field in the class, not inside a method

2024-05-26 22:35 UTC, xenohedron approved these changes

2024-05-26 23:59 UTC, merged