Implement [ACR] Kassandra, Eagle Bearer
magefree/mage pull request #12488
Opened 2024-06-20 05:05 UTC by grimreap124

https://scryfall.com/card/acr/59/kassandra-eagle-bearer

2024-06-20 14:01 UTC, theelk801 requested changes

2024-06-20 14:01 UTC, theelk801 commented on Mage/src/main/java/mage/filter/predicate/permanent/LegendaryEquippedPredicate.java
> +                .allMatch(attachment -> attachment.hasSubtype(SubType.EQUIPMENT, game) && attachment.isLegendary());
use `isLegendary(game)`

2024-06-25 01:01 UTC, xenohedron commented on Mage/src/main/java/mage/filter/predicate/permanent/LegendaryEquippedPredicate.java
> +        return "equipped";
I don't know if this string is actually used for anything, but a more accurate wording would be a good idea

2024-06-26 02:52 UTC, xenohedron commented on Mage.Sets/src/mage/cards/k/KassandraEagleBearer.java
> +        this.addAbility(new DealsDamageToAPlayerAllTriggeredAbility(new DrawCardSourceControllerEffect(1), equipFilter, false, null, true));
still need to replace null with an enum value (which one doesn't matter here) - common code style is to use switch statement on enum and null breaks that, which would be bad if anyone used this as a reference somewhere else

2024-06-26 02:52 UTC, xenohedron commented
also if you can go ahead and merge master to fix conflicts when you are pushing a fix, that saves me time

2024-06-26 03:43 UTC, grimreap124 commented
> also if you can go ahead and merge master into your branch to fix conflicts when you are pushing a fix, that saves me time

I'll start updating if I see merge conflicts

2024-06-26 04:47 UTC, xenohedron commented on Mage.Sets/src/mage/sets/AssassinsCreed.java
>          cards.add(new SetCardInfo("Kassandra, Eagle Bearer", 59, Rarity.MYTHIC, mage.cards.k.KassandraEagleBearer.class));
okay but when you merge, keep it in alphabetical order

2026-05-12 04:25 UTC, xenohedron commented
implemented by 5fcc037c

2026-05-12 04:25 UTC, closed without merging