Rottenmouth Viper
magefree/mage pull request #12718
Opened 2024-08-24 14:10 UTC by Momo2907

Messed up the commit history a bit, the work on Helga, Skittish Seer is currently on another branch in the forked repo.
Played a couple games with the card against a bot and it seems to be working properly.
The implementation for the CostModificationAbility is based on Dargo, the Shipwrecker.
The implementation for the EntersOrAttacksAbility is based on Torment of Hailfire.

2024-08-24 19:56 UTC, xenohedron requested changes

2024-08-24 19:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +class RottenmouthViperCostModificationWatcher extends Watcher {
seems overimplemented, Dargo needs a watcher but this doesn't, see Torgaar, Famine Incarnate

2024-08-24 19:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +                                "Otherwise you lose 4 life.", "Discard", "Lose 3 life", source, game)) {
4 life

2024-08-24 19:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +        this.blightCounterAmount = effect.blightCounterAmount;
copy()

2024-08-24 19:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +    public RottenmouthViperEffect(DynamicValue blightCounterAmount) {
internal custom class, no public modifier here

2024-08-26 01:40 UTC, xenohedron approved these changes

2024-08-26 03:13 UTC, merged

2024-08-26 03:13 UTC, xenohedron commented
thanks for the contribution

2024-08-26 03:59 UTC, JayDi85 reviewed
AI related things also important for complex cards

2024-08-26 03:59 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +                        if (permanents > 0 && opponent.chooseUse(outcome, "Sacrifices a nonland permanent? (Iteration " + i + " of " + repeat + ")",
AI works bad with default outcome (`Outcome.LoseLife`). It's good practice to use custom outcome for each inner choose.

Must use `Outcome.Benefit` so AI will use sacrifice instead loose life all the time. In ideal world it's better to insert more complex logic like if opponent life > 10 then use else not use, but Outcome.Benefit is minimum.

2024-08-26 03:59 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +                            if (opponent.choose(outcome, target, source, game)) {
But not here. It must use bad outcome cause it choose card to sacrifice. So must use `Outcome.Sacrifice`.

2024-08-26 03:59 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +                        if (!opponent.getHand().isEmpty() && opponent.chooseUse(outcome, "Discard a card? (Iteration " + i + " of " + repeat + ")",
Same here. Must Outcome.Benefit so AI will discard instead loose life all the time.

2024-08-30 13:50 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/r/RottenmouthViper.java
> +                        if (permanents > 0 && opponent.chooseUse(outcome, "Sacrifices a nonland permanent? (Iteration " + i + " of " + repeat + ")",
Added AI hints by 84db421f6dde227d635de7d6a4b28f9a7df1861c