update August 26th 2024 B&R cards
magefree/mage pull request #12739
Opened 2024-08-26 20:17 UTC by wajihbenslama

update B&R(26/08/2014) for Modern, Pioneer, Vintage and Legacy

2024-08-26 20:25 UTC, xenohedron requested changes
Please maintain alphabetical order

2024-08-26 20:52 UTC, wajihbenslama commented
list alphabetically ordered

2024-08-26 21:08 UTC, xenohedron approved these changes

2024-08-27 05:02 UTC, merged

2024-08-27 05:03 UTC, xenohedron commented
thanks for the contribution