[M3C] Implement Desert Warfare
magefree/mage pull request #12749
Opened 2024-08-28 19:13 UTC by Sidorovich77

https://scryfall.com/card/m3c/64/desert-warfare

2024-08-30 02:03 UTC, xenohedron requested changes

2024-08-30 02:03 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        if (((ZoneChangeEvent) event).getToZone() == Zone.GRAVEYARD
don't repeat checks in both branches of an if-else, perform the common checks first. return false at everything that doesn't trigger, and only have a single setTargetPointer at the end before returning true

also it's simpler to declare `ZoneChangeEvent zEvent = (ZoneChangeEvent) event` so you only have to cast once

2024-08-30 02:03 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        FilterCard filter = filterCard.copy();
FilterOwnedCard exists.

This is a custom class, so it should include the card name, and params should just be hardcoded.

2024-09-23 22:56 UTC, xenohedron requested changes

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        return new PermanentsOnBattlefieldCount(new FilterControlledPermanent(SubType.DESERT)).calculate(game, sourceAbility, null);
Don't wrap this in a custom class. Declare it as `private static final DynamicValue xValue` and likewise for the hint

2024-09-23 22:56 UTC, xenohedron commented on Mage/src/main/java/mage/abilities/hint/common/DesertsYouControlHint.java
> +
Remove these empty files

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        if (source.getControllerId() == null) {
what's the point of this null check?

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +class DesertWarfareReturnEffect extends OneShotEffect {
why do you actually need a custom class, won't `ReturnFromGraveyardToBattlefieldTargetEffect` suffice?

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        filter.add(targetController.getOwnerPredicate());
there is no point in copying the filter and adding a redundant predicate

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +    public DesertWarfareTriggeredAbility(Zone zone, Effect effect, boolean optional, TargetController targetController, SetTargetPointer setTargetPointer) {
this is a custom class so hardcode all the params and remove the ones you don't need

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +        filterCard = filterCard.copy();
don't copy static member (it should be final anyway)

2024-09-23 22:56 UTC, xenohedron commented on Mage.Sets/src/mage/cards/d/DesertWarfare.java
> +                if (permanent == null || !permanent.hasSubtype(SubType.DESERT, game)) {
you're missing playerid check

2026-05-12 02:10 UTC, muz commented
Probably worth closing this one out as superseded by https://github.com/magefree/mage/pull/13628 which looks mechanically closer to a correct card implementation. There's some pending comments around the test to address still though

2026-05-12 04:10 UTC, closed without merging