Adding The tale of Tamiyo (v1.0)
magefree/mage pull request #13086
Opened 2024-11-27 15:31 UTC by frafen

Adding The tale of Tamiyo from Duskmourn.

2024-11-28 20:03 UTC, xenohedron requested changes

2024-11-28 20:03 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TheTaleOfTamiyo.java
> +        this.filter = new FilterCard("instant, sorcery, or Tamiyo planeswalker card");
make the filter `static` and put this initialization in a `static` block after it, not in the constructor.

2024-11-28 20:03 UTC, xenohedron commented on Mage.Sets/src/mage/cards/t/TheTaleOfTamiyo.java
> +                    while (controller.canRespond() && continueCasting && !copiedCards.isEmpty()) {
Do not use a while loop for this. Instead, use Integer.MAX_VALUE for the max number of targets in the target card, so all the cards to cast can be selected at once. Then for the casting process iterate through those targets with a for loop.

2024-11-29 16:35 UTC, frafen commented on Mage.Sets/src/mage/cards/t/TheTaleOfTamiyo.java
> +                    // Protection against infinity loops
I don't know either, I copy/pasted it from Grindstone's code (that is the base of this effect's code)

2024-11-29 16:54 UTC, frafen commented on Mage.Sets/src/mage/cards/t/TheTaleOfTamiyo.java
> +            } while (controller.getLibrary().size() >= 2); // Continue if there are at least 2 cards left in the library
I think that I can fix this. For the other requests I'm afraid I can't do much, my coding experience is almost nonexistant. I tried to fix some of those other problems with the help of Chat gpt but I'm not having much success.

2024-12-01 01:27 UTC, closed without merging