init i18n support and simplified Chinese translation
magefree/mage pull request #6323
Opened 2020-02-29 06:34 UTC by CCTV-1

some font changes may not be needed(but it is too much trouble to test one by one).

if plan add new language:
`to Mage.Client/src/main/java/mage/client/dialog/PreferencesDialog.java add iso639 lang code string to cbPreferedGUILanguage Model` then: 'add translation file to lMage.Client/languages/ dir'
the Effect:
![en image](https://user-images.githubusercontent.com/7350506/75602472-8522cf00-5b00-11ea-8991-73dad3406e49.png)
![zh image](https://user-images.githubusercontent.com/7350506/75602473-88b65600-5b00-11ea-8921-535647c8f8ee.png)

2020-02-29 08:17 UTC, JayDi85 requested changes
Xmage architect created for one language dozen years ago only and do not support translation.

1. All GUI dialogs are [swing components](https://en.wikipedia.org/wiki/Swing_(Java)) and their auto-generated by IDE (NetBeans) after every change by designer (`*.form` file transforms to `*.java` file):
![shot_200229_111422](https://user-images.githubusercontent.com/8344157/75603090-ad9cd000-5ae4-11ea-91a7-036eb32d4100.png)

All changes in java will be replaced by designer:
![shot_200229_110907](https://user-images.githubusercontent.com/8344157/75603100-c7d6ae00-5ae4-11ea-97d9-df214a32ab56.png)
![shot_200229_110948](https://user-images.githubusercontent.com/8344157/75603102-cb6a3500-5ae4-11ea-9653-ed4d6a870b94.png)

So you must use [netbeans tools for swing](https://netbeans.org/kb/docs/java/gui-automatic-i18n.html): 

![shot_200229_115645](https://user-images.githubusercontent.com/8344157/75603784-34ed4200-5aeb-11ea-8bd6-4b74098eb7d0.png)
![shot_200229_115253](https://user-images.githubusercontent.com/8344157/75603785-3585d880-5aeb-11ea-846b-a75fa5e38629.png)
![shot_200229_115618](https://user-images.githubusercontent.com/8344157/75603705-88ab5b80-5aea-11ea-9d9a-95d4fd9e998a.png)

2. Use only NetBeans version 8 to edit dialog files and enable i18n in it. WARNING, not all forms can be opened by NetBeans (1-2 forms created by IntelliJ designer, 5-6 forms are broken after java only changes outside from IDE, see below).

3. Check every form's changes after i18s support added -- some forms was incorrectly changed before by java only without `*.form` file. So after your edit it will be auto-generated and missed that changes. Report that broken forms on github (it can be fixed by adding all missing changes manually from IDE).

4. I recommends to implemented i8n form by form. E.g. make small proof of concept and then start to implement all other forms.

5. I'm also concerned about replacing the different fonts with non standard and windows only [Microsoft YaHei](https://en.wikipedia.org/wiki/Microsoft_YaHei). Maybe it must be i18n too (I don't research that feature yet).
![shot_200229_104859](https://user-images.githubusercontent.com/8344157/75604088-8ba84b00-5aee-11ea-8c94-c75c70ec9860.png)

6. Small bug:
![shot_200229_104704](https://user-images.githubusercontent.com/8344157/75604202-d8405600-5aef-11ea-839f-dd8b0990ef5b.png)

2020-02-29 08:56 UTC, CCTV-1 commented
I try later use NetBeans make swing components i18n.

fonts that only support at least English cannot support i18n.

if cannot find Microsoft YaHei,should be auto fallback to system font(guess)

2020-02-29 13:19 UTC, CCTV-1 commented
https://github.com/magefree/mage/pull/6323/commits/1ebf70b795902fff761ffa533482266cc9d52c00 this change work on my computer,but in IDE design view will <user code> Instead of english text.

2020-02-29 13:45 UTC, JayDi85 commented
Nope, it doesn't work. 
![shot_200229_174301](https://user-images.githubusercontent.com/8344157/75608686-1dc64880-5b1b-11ea-890c-f009260df3e1.png)



Look at this tutorial to enable i18n by NetBeans 8:
https://netbeans.org/kb/docs/java/gui-automatic-i18n.html

If you follow tutorial and enable i18n then you can edit and view text by IDE as normal text, IDE will automaticity generate all bundle/resource code on save.

2020-02-29 15:30 UTC, CCTV-1 commented
I don't know what is wrong,my netbeans project can't see Mage.Client/languages/*.properties, can see Mage.Client/src/main/java/mage/*.properties.

2020-03-01 04:09 UTC, CCTV-1 commented
https://github.com/magefree/mage/pull/6323/commits/2149065141ee9d18eefca117149077914507486d this change,i can view en/zh text in IDE,but if build then run

zh_CN locale:
`java.util.MissingResourceException: Can't find bundle for base name languages/SwingTranslation, locale zh_CN`

en_US locale:

`java.util.MissingResourceException: Can't find bundle for base name src/main/java/mage/client/dialog/Bundle, locale en_US`

2020-03-01 10:50 UTC, CCTV-1 commented
@JayDi85 these three dialog seems to succeed,can you test it?

2020-03-01 15:07 UTC, JayDi85 commented
> these three dialog seems to succeed,can you test it?

I'll test and check all changes later today/tomorrow -- it need time to read all that changes.

> for others string not contain in swing components ,how to i18n,have other ideas?

Read internationalizing tutorial I posted above -- it contains instructions for non form strings (how to add that strings in bundle): [Internationalizing a Single Form](https://netbeans.org/kb/docs/java/gui-automatic-i18n.html#Exercise_3)

2020-03-01 15:56 UTC, JayDi85 commented
When you replace string with params then use `String.format("Message example %3$s %1$s %2$s", param1, param2, param3)` with ONE const message from bundle. That const message must contains params to insert. Different languages can use different param orders. [Java support it](https://stackoverflow.com/a/6891209/1276632).

2020-03-03 16:30 UTC, JayDi85 commented
1. Do not translate static constants -- language switch will not work after that (use dynamic values in code like `String RATED_VALUE_YES = xxx` or make it as class field and update on `changeGUISize()`):
`public static final String RATED_VALUE_YES = java.util.ResourceBundle.getBundle("otherMessage").getString("lblYes");`

2. Do not translate hotkeys, only text/description:
`<html><b>F3</b> - `

2020-03-04 01:00 UTC, CCTV-1 commented
> 1. Do not translate static constants -- language switch will not work after that (use dynamic values in code like `String RATED_VALUE_YES = xxx` or make it as class field and update on `changeGUISize()`):
>    `public static final String RATED_VALUE_YES = java.util.ResourceBundle.getBundle("otherMessage").getString("lblYes");`
> 2. Do not translate hotkeys, only text/description:
>    `<html><b>F3</b> - `

for Swing widget text,it seems that it can only be tell translators do not translate hotkeys.

2020-03-09 12:39 UTC, CCTV-1 commented
@JayDi85 already ready(xmage.vip user test it,no problems found after using it for a few days)

2020-03-25 13:21 UTC, geektcp requested changes
That is best to commit one pull request for one feature

2020-03-26 01:28 UTC, CCTV-1 commented
> That is best to commit one pull request for one feature

the simplified chinese translation no code changes,will not give code review cause trouble.

2026-07-20 10:30 UTC, JayDi85 commented
Current gui has too much texts and created without i18n design. Also it’s impossible to translate game dialogs and logs cause it depends on English cards. It’s hard to support. So no needs in translations.

2026-07-20 10:30 UTC, closed without merging