[KHM] Implemented Realmwalker
magefree/mage pull request #7279
Opened 2020-12-23 09:08 UTC by weirddan455

Implemented Realmwalker for #7248 

I used code from `PlayTheTopCardEffect`.  Just needed to change a couple of lines to move the filter to `applies` in order to check against the chosen creature type.

2020-12-23 09:43 UTC, weirddan455 commented
Pushed another commit that should fix the build error:

`Error: (abilities) card has Changeling but doesn't have isAllCreatureTypes set to true for KHM - Realmwalker - 188`

It built successfully on my machine which is kind of strange.

2020-12-23 13:39 UTC, JayDi85 commented
It's a verify tests from Mage.Varify project. It uses cards database from [mtgjson](https://mtgjson.com/) and checks some data. So you must find and delete `\Mage.Verify\AllPrintings.json.zip` file -- it will be re-downloaded with newest data.

2020-12-25 06:46 UTC, JayDi85 requested changes
There is already exists the special predicate `ChosenSubtypePredicate.instance` for chosen filter (example: `KindredDiscovery`). So can you try to use standard `PlayTheTopCardEffect` effect instead custom (example: `ConspicuousSnoop`)?

2020-12-25 06:50 UTC, JayDi85 commented on Mage.Sets/src/mage/cards/r/Realmwalker.java
> +        filter.add(ChooseCreatureTypeEffect.getChosenCreatureType(source.getSourceId(), game).getPredicate());
You must check chosen result for `null`

2020-12-25 15:05 UTC, weirddan455 commented
I just tested using `ChosenSubtypePredicate.instance` and `PlayTheTopCardEffect` but for some reason, the predicate won't apply.  I even tested hardcoding `return false;` into `ChosenSubTypePredicate.java` and the result is that it lets me cast any creature off the top.

Other cards using this predicate work (tested Belbe's Portal) so I'm not sure why this doesn't.

Anyway, I just pushed a commit adding the null check but if you have any ideas about how to get this predicate to work (or how to create a new predicate that works for this card), let me know.  That does seem like a cleaner solution.

2020-12-25 15:08 UTC, JayDi85 commented
I added some improved by a307e5934f850b8936774a95787d4978d69ee179 (`PlayTheTopCardEffect` now check full filter), so try latest sources. It must works fine.

2020-12-25 16:17 UTC, weirddan455 commented
Nice, that fixed it.  Latest commit removes the custom effect and uses `PlayTheTopCardEffect`.

2020-12-25 16:40 UTC, JayDi85 approved these changes

2020-12-25 16:40 UTC, merged