Fixed Wording on 2 cards and removed duplicate StaticFilter
magefree/mage pull request #8596
Opened 2022-01-25 23:17 UTC by Alex-Vasile

1. Fixed wording on creature selection for Enthralling Hold ("a creature" -> "a tapped creature")
2. Fixed wording on permanent selection for Dream Leash ("a permanent" -> "a tapped permanent")
3. Removed FILTER_PERMANENT_CREATURE_A since FILTER_PERMANENT_A_CREATURE already existed and they both did the exact same thing.

2022-01-25 23:32 UTC, awjackson requested changes
Please re-check the Oracle text for Dream Leash and Enthralling Hold. They have "enchant permanent", not "enchant tapped permanent". They only check that the target is tapped when you cast them; they don't fall off if the enchanted permanent becomes untapped later (as they would if they had "enchant tapped permanent").

2022-01-25 23:42 UTC, Alex-Vasile commented
Sigh. My bad. Still haven't gotten the hang on where each of those texts pop up.

What I was trying to do was fix the text that's shown to a player when they select the target creature/permanent during casting (based on #6643), not the text on the card.

2022-01-25 23:57 UTC, awjackson commented
Yeah, a lot of cards throughout xmage have ended up with wrong card text because whoever implemented them tried to use "friendlier" filter strings for targetting.

2022-01-26 00:00 UTC, Alex-Vasile commented
Is there support for having a different filter string for targeting than that on the card?

2022-01-26 00:08 UTC, awjackson commented
You can use the `Target.withChooseHint` method to add a message that will be displayed in parentheses when choosing the target. It's mainly meant for spells that have multiple targets and apply different effects to each target, but for these cards you could add a "can't be untapped" hint.

2022-01-26 01:57 UTC, Alex-Vasile commented
Alright, made those changes. I also went with "must be tapped" to avoid the double negative.

2022-01-26 02:08 UTC, merged