Adds 15 Pride flags to countrybox selection [UNTESTED]
magefree/mage pull request #8937
Opened 2022-05-10 08:43 UTC by chesse20

I've never used maven (and "mvn install -DskipTests" doesn't seem to do anything in visual studio code) and i haven't touched java in like 3 years but after looking over the code this might add 15 pride flags to select instead of countries, for those who care more about their pronouns, identity, and/or support for their lgbtq+ friends over displaying their country of origin.

2022-05-10 23:41 UTC, chesse20 commented
![image](https://user-images.githubusercontent.com/9161779/167741807-0a6accf3-ec8a-4f1a-bfad-1bec49378377.png)
i got step on this step in the visual studio code set-up so i can't test the code yet

2022-05-14 07:28 UTC, chesse20 commented
> > ![image](https://user-images.githubusercontent.com/9161779/167741807-0a6accf3-ec8a-4f1a-bfad-1bec49378377.png)
> > i got step on this step in the visual studio code set-up so i can't test the code yet
> 
> I haven't tried VSC since I only use IntelliJ.
> 
> Have you tried the instructions [here](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#visual-studio-code-vsc)?

yeah i followed the instructions a bit better and got to around step 9 but got a bunch of errors and couldn't figure out how to get the client to run. ill try it again tommorow

2022-05-14 08:51 UTC, chesse20 commented
![image](https://user-images.githubusercontent.com/9161779/168418581-d3317678-06af-4580-822b-eec89658df14.png)
idk how to run the client from here

2022-05-17 16:50 UTC, Alex-Vasile commented
> ![image](https://user-images.githubusercontent.com/9161779/168418581-d3317678-06af-4580-822b-eec89658df14.png)
> idk how to run the client from here



> ![image](https://user-images.githubusercontent.com/9161779/168418581-d3317678-06af-4580-822b-eec89658df14.png)
> idk how to run the client from here

I would venture a guess and say that you have to hover over "mage-client" in the "JAVA PROJECT" dropdown there and press the play button (after you've built it with maven).

2022-05-17 16:50 UTC, Alex-Vasile commented
> ![image](https://user-images.githubusercontent.com/9161779/168418581-d3317678-06af-4580-822b-eec89658df14.png)
> idk how to run the client from here



> ![image](https://user-images.githubusercontent.com/9161779/168418581-d3317678-06af-4580-822b-eec89658df14.png)
> idk how to run the client from here

I would venture a guess and say that you have to hover over "mage-client" in the "JAVA PROJECT" dropdown there and press the play button (after you've built it with maven).

2022-05-20 08:08 UTC, peter-thoenen commented
Can we vote no to not "woken" Xmage, if I wanted that I would go give Hasbro my money.  Last I checked we already have a pride flag, it's called France.  We don't need more because it opens up the flood doors to every one elses pet flags and causes. Do we add political party flags? universities? etc etc.

2022-05-20 20:38 UTC, chesse20 commented
im gonna try this with intelej, been busy with finals so i haven't had much energy but im trying to get this done before pride month

2022-07-05 18:00 UTC, the-red-lily requested changes

2022-07-05 18:00 UTC, the-red-lily commented on Mage.Client/src/main/java/mage/client/util/gui/countryBox/CountryComboBox.java
> +        {"Pansexual","pan"}
Missing ,

2023-01-12 10:22 UTC, chesse20 commented
i fixed some issues with the file and managed to compile the master branch, but something about this code causes the server files to not compile. i got no clue whats wrong with

2023-04-28 04:12 UTC, xenohedron approved these changes
I tested this and found no issues. Hope it can be merged soon.

2023-05-01 19:05 UTC, Grath commented
Can someone compile it and test with a server? I'm seeing the pride flags in the client in the Connect window, but I don't see them rendering properly when connected to the server (and I don't know what's broken there, whether it's my end or an issue with this pull request.)

2023-05-01 23:36 UTC, xenohedron reviewed
@chesse20 @Grath
I tested more thoroughly and also found that the flag images are not rendering correctly once connected to the server. I guess more investigation is needed there.

2023-05-02 01:36 UTC, chesse20 commented
yeah i can't find any flag code related to the server so im confused what i could be missing

2023-06-07 22:12 UTC, alexander-novo commented
Works fine for me

![image](https://github.com/magefree/mage/assets/11657716/99bb5372-5f95-4cc2-8674-518ced58915f)

![image](https://github.com/magefree/mage/assets/11657716/3fa1596b-5058-4b3a-9609-e49f08248548)

I merged master in to the branch before building.

2023-06-07 22:51 UTC, xenohedron commented
Great! I just tested it again and it worked fine for me this time. No idea what was going on before.

2023-06-07 22:51 UTC, merged