Stops auto-payment of mana for sunburst spells
magefree/mage pull request #9173
Opened 2022-06-27 19:39 UTC by Alex-Vasile

Spells with sunburst care about the color choices being made.

This PR stops mana from being auto-paid and colors from being auto-chosen.

Closes #9070.

2022-06-27 19:58 UTC, emerald000 commented
It's probably better to add a flag to abilities that care about which colours you use. There are other cards such as Firespout and friends, and the Adamant ability.

2022-06-27 20:35 UTC, Alex-Vasile commented
> It's probably better to add a flag to abilities that care about which colours you use. There are other cards such as Firespout and friends, and the Adamant ability.

Good point. I had completely forgotten about those. I will draw up a list and add a flag to them.

2022-06-29 01:26 UTC, Alex-Vasile commented on Mage/src/main/java/mage/abilities/effects/EffectImpl.java
> +                // TODO: I don't think I should get to here
Not sure if something is needed here. Should never really get here.

2022-06-29 05:35 UTC, JayDi85 commented
1. I don’t like THREE diff places for one “field” (card, effect, ability). Must be in one place. Why you can’t keep that field in ability only?

2. Code must be without class/reflect hacks (it definitely restricted for usage in the game engine code without really needs).

3. You must work with dynamic abilities list all the time (e.g. get card abilities with game param).

4. Spell ability in abilities list already, no need to check it specially;

5. Is it compatible with AI games (e.g. AI can play related cards/abilities)?

2022-06-29 13:19 UTC, Alex-Vasile commented
Re 2: The reason I need the reflection is because as currently implemented, the alternative is a chain of long `instanceof` checks for each ability/effect.

Perhaps they should be refactored so that this isn't needed.

2022-07-02 20:12 UTC, Alex-Vasile commented
> * [ ]  1. I don’t like THREE diff places for one “field” (card, effect, ability). Must be in one place. Why you can’t keep that field in ability only?
> * [ ]  2. Code must be without class/reflect hacks (it definitely restricted for usage in the game engine code without really needs).
> * [x]  3. You must work with dynamic abilities list all the time (e.g. get card abilities with game param).
> * [x]  4. Spell ability in abilities list already, no need to check it specially;
> * [ ]  5. Is it compatible with AI games (e.g. AI can play related cards/abilities)?

Re 1: I have it in multiple places for a few reasons:
- The CardImpl: there so that I don't have to copy and paste code inside HumanPlayer. I need to perform this check in two difference places, so I will need a helper method somewhere, and having it in the Card class made more sense than in the HumanPlayer class
- Ability and Effect:
    - Sunburst and Modular are implemented as abilities
    - Adamant and "If {R} is spent do X, if {W} is spend to Y, if both {R}{W} are spend to X and Y" are implemented as conditional effects.

But, I think I can refactor checks out of Effects class and have the ability class check all of it's effects to see if they care about mana color.

I can get it down to: Card, Ability, Condition.

2022-07-02 20:13 UTC, Alex-Vasile commented
Re 5: This only affects the human player

2022-09-27 14:40 UTC, Alex-Vasile commented
Potential TODO: add hint to stack objects which care about color cast which indicate the current colors spent (as well as a total) in paying the cost.

I think that would be usefull, does it belong in this PR?

2022-09-27 16:20 UTC, awjackson commented
Aesthetically I don't really like how this has to be set per-card and not strictly per-ability, but because of how many of these are ETB abilities of permanents I suppose it can't be helped. However, I think all or almost all of the manual overrides can be removed with a little more work:

- In all per-card custom `Effect` subclasses that care about colored mana, override `Effect.getCondition` to return the appropriate mana condition (if there are two, like the Shadowmoor cycle, it's fine to just return one of them).

- Override the `caresAboutManaColor` methods of `LockedInCondition` and `CompoundCondition` to pass through from the wrapped `Condition` (or the logical OR of all the wrapped conditions for the latter).

2022-09-27 16:21 UTC, awjackson requested changes
Aesthetically I don't really like how this has to be set per-card and not strictly per-ability, but because of how many of these are ETB abilities of permanents I suppose it can't be helped. However, I think all or almost all of the manual overrides can be removed with a little more work:

- In all per-card custom `Effect` subclasses that care about colored mana, override `Effect.getCondition` to return the appropriate mana condition (if there are two, like the Shadowmoor cycle, it's fine to just return one of them).

- Override the `caresAboutManaColor` methods of `LockedInCondition` and `CompoundCondition` to pass through from the wrapped `Condition` (or the logical OR of all the wrapped conditions for the latter).

2022-10-03 22:30 UTC, awjackson approved these changes

2022-10-03 23:16 UTC, merged