[DMU] Implement Thran Portal
magefree/mage pull request #9456
Opened 2022-09-02 01:09 UTC by Alex-Vasile

2022-09-02 01:33 UTC, Alex-Vasile commented
> does this work with [[Urborg, Tomb of Yawgmoth]] or [[Chromatic Lantern]]?

I can add tests, but I am not sure why it wouldn't. What is the interaction you're worried about?

2022-09-02 01:35 UTC, theelk801 commented
the extra abilities they add should cost life to activate

2022-09-02 01:37 UTC, theelk801 commented
also you shouldn’t add the cost to the abilities because they don’t actually have the cost

2022-09-02 02:02 UTC, Alex-Vasile commented
> also you shouldn’t add the cost to the abilities because they don’t actually have the cost

I don't understand what you mean

2022-09-02 02:13 UTC, theelk801 commented
the abilities don’t actually have “pay 1 life” added to them, there’s just an effect that requires you to pay an additional life when you activate, so [[Manascape Refractor]] should copy them abilities without needing to pay life

2022-09-02 02:16 UTC, Alex-Vasile commented
I get you. Okay, will change that as well and base it off [[Brutal Suppression]]

2022-09-04 17:02 UTC, Alex-Vasile commented
> the abilities don’t actually have “pay 1 life” added to them, there’s just an effect that requires you to pay an additional life when you activate, so [[Manascape Refractor]] should copy them without needing to pay life

done

2022-09-04 18:41 UTC, theelk801 requested changes
looks good to me apart from the two small notes I added

2022-09-04 18:41 UTC, theelk801 commented on Mage.Sets/src/mage/cards/t/ThranPortal.java
> +        staticText = "mana abilities of Thran Portal cost an additional 1 life to activate";
don't forget to use `{this}`

2022-09-04 18:41 UTC, theelk801 commented on Mage.Sets/src/mage/cards/t/ThranPortal.java
> +        this.staticText = "mana abilities of Thran Portal cost an additional 1 life to activate";
also here

2022-09-04 18:50 UTC, theelk801 approved these changes

2022-09-04 18:50 UTC, merged