Change EnchantAbility constructor parameter from String to Target
magefree/mage pull request #9588
Opened 2022-09-28 08:19 UTC by awjackson

This is the first necessary step toward resolving #9583 . Because of the large number of files affected and because it's a Flag Day for all new card implementations (at least the new cards that are Auras) this PR *only* does the bare minimum of changing the constructor parameter, in order to get it merged as quickly and smoothly as possible.

2022-09-28 12:55 UTC, Alex-Vasile commented
I'm gonna look through this. But it will be a little slow since GitHub (the website) apparently does not scale well beyond 200-300 changed files.

What does this refactor achieve? Can you layout how you plan of fixing #9583? Or even branch off of this branch, implement the fix and then open a separate PR so that we can see how this is used.

2022-09-28 13:33 UTC, awjackson commented
Once this is in place, the next step is to actually store a copy of the `Target` argument as a field in `EnchantAbility`. Then, every place in the engine that is currently getting a `Target` from an Aura's `SpellAbility` can be changed to get it from the Aura's `EnchantAbility` instead. That includes most prominently the SBA code, but also several common filter `Predicate`s and a bunch of per-card custom code (e.g. cards that cheat Auras onto the battlefield or move them from one object to another).

2022-09-29 13:23 UTC, Alex-Vasile requested changes

2022-09-29 14:11 UTC, awjackson commented on Mage/src/main/java/mage/abilities/common/LicidAbility.java
> -                    target.addTarget(this.getTargetPointer().getFirst(game, source), source, game);
It was never needed (maybe it was at some point, but not now) That line sets the state of the Target object to be as if the player had chosen that creature as a target while casting the spell, but that doesn't matter anywhere.

2022-09-29 14:24 UTC, Alex-Vasile approved these changes

2022-09-29 14:29 UTC, merged