[CLB] Implemented Vhal, Candlekeep Researcher
magefree/mage pull request #9865
Opened 2023-01-04 16:08 UTC by PCMSec

2023-02-08 20:19 UTC, PurpleCrowbar requested changes

2023-02-08 20:19 UTC, PurpleCrowbar commented on Mage.Sets/src/mage/cards/v/VhalCandlekeepResearcher.java
> +
The tap source cost is not necessary for abilities of ConditionalColorlessManaAbility type as they have a tap source cost by default, so line 43 can be removed. Additionally, you have to add this ability to the card using `this.addAbility(ability)`

2023-02-08 20:19 UTC, PurpleCrowbar commented on Mage.Sets/src/mage/cards/v/VhalCandlekeepResearcher.java
> +            return false;
This should return true as the condition allows the mana to be spent on abilities

2023-02-09 21:53 UTC, PCMSec commented
Added the necessary changes

2023-02-09 23:55 UTC, PurpleCrowbar requested changes

2023-02-09 23:55 UTC, PurpleCrowbar commented on Mage.Sets/src/mage/cards/v/VhalCandlekeepResearcher.java
> +        staticText = "This mana can’t be spent to cast spells from your hand";
One more thing, in this string on line 76 and on the one on line 68 you have to replace the Scryfall apostrophe in the word "can't" with a regular apostrophe.

2023-02-10 14:43 UTC, PCMSec commented
Done, thanks for the feedback

2023-02-10 21:53 UTC, merged

2023-02-10 21:54 UTC, PurpleCrowbar commented
Thanks for the contribution