Gleeful demolition
magefree/mage pull request #9896
Opened 2023-01-21 07:31 UTC by AhmadYProjects

2023-01-21 07:32 UTC, AhmadYProjects commented
[[Gleeful Demolition]]

2023-01-21 14:30 UTC, theelk801 requested changes

2023-01-21 14:30 UTC, theelk801 commented on Mage.Sets/src/mage/cards/g/GleefulDemolition.java
> +
don't forget the super constructor here

2023-01-21 14:30 UTC, theelk801 commented on Mage.Sets/src/mage/cards/g/GleefulDemolition.java
> +class GleefulDemolitionEffect extends DestroyTargetEffect {
this doesn't really need to extend `DestroyTargetEffect`, it can just be a `OneShotEffect`

2023-01-22 03:33 UTC, theelk801 requested changes

2023-01-22 03:33 UTC, theelk801 commented on Mage.Sets/src/mage/cards/g/GleefulDemolition.java
> +        return super.apply(game,source);
this super call doesn't do anything anymore, replace it with `return true` and add `permanent.destroy` between lines 73 and 74

2023-01-22 15:06 UTC, merged